export const GET_QUESTION_LIST = "GET_QUESTION_LIST";
export const GET_QUESTION_LIST_SUCCESS = "GET_QUESTION_LIST_SUCCESS";
export const GET_QUESTION_LIST_FAILED = "GET_QUESTION_LIST_FAILED";
export const CHANGE_SCORE = "CHANGE_SCORE";
export const RESTART_QUIZ = "RESTART_QUIZ";
export const CHANGE_ATTEMPTQUESTION = "CHANGE_ATTEMPTQUESTION";
export const SELECTED_ANSWER = "SELECTED_ANSWER";
